### PR TITLE
Fix: React Collabocate UI library not yet able to submit issue tickets

### LINKED ISSUE #65: React Collabocate UI library not yet able to submit issue tickets
#### Issue description

The library is not having the functionality to submit issue tickets. This feature should be added to allow users to create and submit tickets.

#

#### Steps to reproduce the issue

1. Plug in the Collabocate UI plugin library into the web client
2. Click 'Submit Issue Ticket' button.
3. See that the button does not yet submit to the backend api-server.

#

#### Expected behavior

The library should make use of the backend api-server, to successfully submit issue tickets to the `use-me-for-experiments` repo, once the 'Submit Issue Ticket' button is clicked on.

#

#### Additional context

Repo URL (collabocate): https://github.com/collabocate/react

#

#### Testing checklist

Note (to contributor taking on this task assignment): Add the testing checklist below (without this note) to your pull request when submitting your fix. This will guide (you and) the contributors who will review your fix to know what is important to check or test for.
- [ ] The library makes use of the backend api-server, to successfully submit issue tickets to the `use-me-for-experiments` repo, when the 'Submit Issue Ticket' button is clicked on.
- [ ] I certify that I ran my checklist

### PR DESCRIPTION
**Pull request by KBandipo**
#### This pull request makes the following changes

* Fixes collabo-community/issue-tickets-ready-for-fixing#65

#

#### General checklist

- [x] My pull request adheres to the [Collabo Community pull request guidelines](https://docs.collabocommunity.com/pull-request-guidelines).
- [x] I have read and understood the **Pull request guideline extension** section found at the bottom of this pull request description/body.
- [x] I have replaced the dummy text under the subheading **Testing checklist** below with the testing checklist from the issue ticket I'm working on.

#

#### Testing checklist

- [x] The library makes use of the backend api-server, to successfully submit issue tickets to the `use-me-for-experiments` repo, when the 'Submit Issue Ticket' button is clicked on.
- [x] I certify that I ran my checklist

#

#### How to run project

The changes here should be tested with api-server PR https://github.com/collabo-community/api-server/pull/14

#

#### Pull request guideline extension

> [!NOTE]  
> Do not remove this note or section. This talks about extra things to take note of, in addition to the directions given in the Collabo Community pull request guidelines.

We appreciate the time taken to help tackle issue tickets within the Collabo Community. Please go ahead to submit your pull request even if it is not yet completed, and push to the pull request actively. This will allow us to know that you have not abandoned the issue ticket. However, you should only alert reviewers about your pull request as explained below, to avoid flooding their GitHub notifications unnecessarily.

"Ready for review" implies that things are working as expected, according to how it is specified in the issue ticket you are working on. Ensure that you test the code that you are working on, that it works as expected. Don't just request for review when your pull request is not yet done and working.

The only time you should be making people review something incomplete is: if you want to show them what's not working, so that they can send help or guidance. If this is the case, be explicit about this in our Discord community or in the comment of your pull request (after you have submitted the pull request).

### CODE REVIEW

**Comment by KBandipo** [comment]
Ready for review

File: src/@core/submitIssue.ts [hunk 1]
```diff
@@ -0,0 +1,11 @@
+import { apiClient } from "./api-client";
+import { IssueData, IssueResponse } from "./types/issueData.types";
```
Comment (Ifycode) [inline src/@core/submitIssue.ts]: Maintain single quotes for consistency @KBandipo

File: src/components/@section_modal/ModalPopup.tsx [hunk 2]
```diff
@@ -38,10 +40,16 @@ export const ModalPopup: React.FunctionComponent<ModalPopupProps> = (props: Moda
...
-            <textarea className="bb-content-group__collabocate_form-inner bb-collabocate_input bb-collabocate_textarea" id="issueBody" value={issueBody}></textarea>
+            <textarea className="bb-content-group__collabocate_form-inner bb-collabocate_input bb-collabocate_textarea" id="issueBody" onChange={(e) =>setIssueBody(e.target.value)} value={issueBody}></textarea>
           </div>
           <button className="bb-content-group__collabocate_form-inner bb-collabocate_submit-form-button" id="submitIssueButton">Submit Issue Ticket</button>
-          <div id="displayToastrMessage"></div>
+           {toastrMessage && (
+            <div
+              id="displayToastrMessage"
+              dangerouslySetInnerHTML={{ __html: toastrMessage }}
+            />
```
Comment (Ifycode) [inline src/components/@section_modal/ModalPopup.tsx]: Why not just use the usual `<div>{{ variableName }}</div>` instead of using the `dangerouslySetInnerHTML` way? @KBandipo

File: src/components/@section_modal/ModalPopup.tsx [hunk 3]
```diff
@@ -38,10 +40,16 @@ export const ModalPopup: React.FunctionComponent<ModalPopupProps> = (props: Moda
...
+          )}
+          {/* <div id="displayToastrMessage"></div> */}
```
Comment (Ifycode) [inline src/components/@section_modal/ModalPopup.tsx]: You can remove the comment here @KBandipo

**Review by Ifycode — CHANGES_REQUESTED** [review]

File: src/@core/types/issueData.types.ts [hunk 4]
```diff
@@ -0,0 +1,13 @@
+export interface IssueData {
+  title: string;
+  body: string;
```
Comment (Ifycode) [inline src/@core/types/issueData.types.ts:3]: Let's make it clear that this is what the user sends... The name of this interface should be something like `Issue_POST_RequestBody`.

File: src/@core/types/issueData.types.ts [hunk 5]
```diff
@@ -0,0 +1,13 @@
...
+}
+
+export interface IssueResponse {
+  message: string;
+  issue:{
+    html_url:string;
+    number: number;
+    body:string;
```
Comment (Ifycode) [inline src/@core/types/issueData.types.ts]: I don't recognise this response shape from our API @KBandipo 
Help identify where you got this from.

**Review by Ifycode — CHANGES_REQUESTED** [review]

File: src/@core/submitIssue.ts (hunk 1 above)
Comment (KBandipo) [reply src/@core/submitIssue.ts]: Ah, I missed that, autocomplete things

File: src/components/@section_modal/ModalPopup.tsx (hunk 2 above)
Comment (KBandipo) [reply src/components/@section_modal/ModalPopup.tsx]: @Ifycode 
Using the variable directly, the link is displaying as text
image

File: src/@core/types/issueData.types.ts (hunk 5 above)
Comment (KBandipo) [reply src/@core/types/issueData.types.ts]: I decided to make use of html_url, number and body(in case of future) from the issue object.
image
image
image

Comment (Ifycode) [reply src/@core/types/issueData.types.ts]: Hmm...

File: src/components/@section_modal/ModalPopup.tsx (hunk 2 above)
Comment (Ifycode) [reply src/components/@section_modal/ModalPopup.tsx:50]: 🤔

Comment (Ifycode) [reply src/components/@section_modal/ModalPopup.tsx]: 🤔 Ok. Try exploring some other means as long as it's not the use of dangerously set html.

File: src/@core/types/issueData.types.ts (hunk 5 above)
Comment (Ifycode) [reply src/@core/types/issueData.types.ts]: Ok, I think we need to cleanup the response similar to how we did for the issue templates. This one for issues should be simpler, because we are only changing the shape of the `issue` object in the api response.
#
Remind me... How did we approach this before?

Comment (KBandipo) [reply src/@core/types/issueData.types.ts]: Okay, I think I remember.
I'll implement it boss

File: src/components/@section_modal/ModalPopup.tsx (hunk 2 above)
Comment (KBandipo) [reply src/components/@section_modal/ModalPopup.tsx]: Copy boss

**Comment by KBandipo** [comment]
Ready for review
@Ifycode

**Comment by KBandipo** [comment]
Ready for review

File: src/@core/types/issueData.types.ts [hunk 6]
```diff
@@ -0,0 +1,14 @@
+export interface Issue_POST_RequestBody {
+  title: string;
+  body: string;
+}
+
+export interface IssueDetails {
+  url:string;
+  number: number;
+}
```
Comment (Ifycode) [inline src/@core/types/issueData.types.ts]: It doesn't make sense to extract this into it's own variable, you can just insert it directly into `IssueResponse` @KBandipo

File: src/components/@section_modal/ModalPopup.tsx [hunk 7]
```diff
@@ -38,10 +40,26 @@ export const ModalPopup: React.FunctionComponent<ModalPopupProps> = (props: Moda
...
+            <div id="displayToastrMessage">
+              {toastrSuccessMessage.message}
+            </div>
+          )}
+          {followIssueMessage && (
+            <div>
+               {followIssueMessage.issueURL && followIssueMessage.issueNumber && (
+                <>
+                  Follow your issue ticket's progress here:{" "}
+                  <a href={followIssueMessage.issueURL} target="_blank" rel="noopener noreferrer">
```
Comment (Ifycode) [inline src/components/@section_modal/ModalPopup.tsx]: **1 of 2:** Wondering why you decided to tamper with this file in the screenshot below @KBandipo 

Screenshot 2025-04-16 at 20 24 51

#

**2 of 2:** Also wondering why this part in the screenshot below changed so much, when the only change/difference I'm expecting is an additional div for the "Follow your issue ticket's progress here..." part of the toastr message.
Screenshot 2025-04-16 at 20 36 16

**Review by Ifycode — CHANGES_REQUESTED** [review]

File: src/@core/types/issueData.types.ts (hunk 6 above)
Comment (KBandipo) [reply src/@core/types/issueData.types.ts]: Copy

File: src/components/@section_modal/ModalPopup.tsx (hunk 7 above)
Comment (KBandipo) [reply src/components/@section_modal/ModalPopup.tsx]: It's really funny, I was using another state to render the second div. I didn't check my logic very well

**Comment by KBandipo** [comment]
Ready for review

File: src/components/@section_modal/ModalPopup.tsx (hunk 7 above)
Comment (Ifycode) [reply src/components/@section_modal/ModalPopup.tsx]: 😉

**Review by Ifycode — APPROVED** [review]
🎉
