### PR TITLE
Fix: Update "Choose Report Type" dropdown's main button text to user's selected Issue template title

### LINKED ISSUE #124: Update "Choose Report Type" dropdown's main button text to user's selected Issue template title
#### Issue description

Currently, when a user selects an issue template from the dropdown, the `-- Select issue template --` text does not update to reflect the selected issue template.

#

#### Steps to reproduce the issue

1. Go to web app that uses a working collabocate plugin instance, and interact with the with Collabocate plugin modal there.
2. From the collabocate plugin modal, click on `-- Select issue template --` dropdown button to select an issue template.
3. Observe that the dropdown main button still displays `-- Select issue template --`  instead of updating to show the selected template.

#

#### Expected behavior

Once a user selects a template, the main dropdown button text should immediately update to display the name of the selected issue template.

#

#### Screenshots

Image

#

#### Additional context

Repo URL: https://github.com/collabocate/react

#

#### Testing checklist

Note (to contributor taking on this task assignment): Add the testing checklist below (without this note) to your pull request when submitting your fix. This will guide (you and) the contributors who will review your fix to know what is important to check or test for.
- [ ] The main dropdown button text updates to the selected issue template title, when a user selects an issue template from the "choose report type" dropdown.
- [ ] I certify that I ran my checklist

### PR DESCRIPTION
**Pull request by KBandipo**
#### This pull request makes the following changes

* Fixes collabo-community/issue-tickets-ready-for-fixing#124

#

#### General checklist

- [x] My pull request adheres to the [Collabo Community pull request guidelines](https://docs.collabocommunity.com/pull-request-guidelines).
- [x] I have read and understood the **Pull request guideline extension** section found at the bottom of this pull request description/body.
- [x] I have replaced the dummy text under the subheading **Testing checklist** below with the testing checklist from the issue ticket I'm working on.

#

#### Testing checklist

- [x] The main dropdown button text updates to the selected issue template title, when a user selects an issue template from the "choose report type" dropdown.
- [x] I certify that I ran my checklist

#

#### Pull request guideline extension

> [!NOTE]  
> Do not remove this note or section. This talks about extra things to take note of, in addition to the directions given in the Collabo Community pull request guidelines.

We appreciate the time taken to help tackle issue tickets within the Collabo Community. Please go ahead to submit your pull request even if it is not yet completed, and push to the pull request actively. This will allow us to know that you have not abandoned the issue ticket. However, you should only alert reviewers about your pull request as explained below, to avoid flooding their GitHub notifications unnecessarily.

"Ready for review" implies that things are working as expected, according to how it is specified in the issue ticket you are working on. Ensure that you test the code that you are working on, that it works as expected. Don't just request for review when your pull request is not yet done and working.

The only time you should be making people review something incomplete is: if you want to show them what's not working, so that they can send help or guidance. If this is the case, be explicit about this in our Discord community or in the comment of your pull request (after you have submitted the pull request).

### CODE REVIEW

**Comment by KBandipo** [comment]
Ready for review

File: src/components/@helpers/dropdown/Dropdown.tsx [hunk 1]
```diff
@@ -29,8 +29,10 @@ export const Dropdown: React.FunctionComponent<DropdownProps> = ({}) => {
           className="bb-content-group_toggle bb-toggle"
           type="button"
           onClick={() => setIsOpen(!isOpen)}
+          onMouseEnter={() => setIsHovering(true)}
+          onMouseLeave={() => setIsHovering(false)}
         >
-          -- Select issue template --
+          {isHovering ? '-- Select issue template --' : buttonTitle}
```
Comment (Ifycode) [inline src/components/@helpers/dropdown/Dropdown.tsx]: Err... What's the need for the hovering text and all the related hover code in general? And is that specified in the ticket? @KBandipo

**Review by Ifycode — CHANGES_REQUESTED** [review]

File: src/components/@helpers/dropdown/Dropdown.tsx (hunk 1 above)
Comment (KBandipo) [reply src/components/@helpers/dropdown/Dropdown.tsx]: After the user selects a template and the button text is updated, the user might want to change the templates again.
I thought the button text should change back to "-- Select issue template --". I was just thinking about the user's experience, but clearly is not part of the ticket.
I'll change it back now

**Comment by KBandipo** [comment]
Ready for review

**Comment by KBandipo** [comment]
Ready for review

File: src/components/@hooks_state/useSubmitIssue.ts [hunk 2]
```diff
@@ -4,12 +4,13 @@ import { submitIssue } from '../../@core/submitIssue';
...
 
 function useSubmitIssueState (){
-  const { issueBody, setIssueBody, issueTitle, setIssueTitle } = GitHubIssueTemplateContainer.useContainer();
+  const { issueBody, setIssueBody, issueTitle, setIssueTitle, setButtonTitle} = GitHubIssueTemplateContainer.useContainer();
   const [toastrMessage, setToastrMessage] = useState<{message: string; issueURL?: string; 
     issueNumber?: number;} | null>(null);
     
   const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
     e.preventDefault();
+    setButtonTitle('-- Select issue template --');
```
Comment (Ifycode) [inline src/components/@hooks_state/useSubmitIssue.ts]: This text is repeated 2ce: `'-- Select issue template --'`. You can save it in a variable for reuse or something.

File: src/components/@helpers/dropdown/Dropdown.tsx [hunk 3]
```diff
@@ -30,7 +30,7 @@ export const Dropdown: React.FunctionComponent<DropdownProps> = ({}) => {
           type="button"
           onClick={() => setIsOpen(!isOpen)}
         >
-          -- Select issue template --
+          {buttonTitle}
```
Comment (Ifycode) [inline src/components/@helpers/dropdown/Dropdown.tsx]: Title should change back to initial text, only when submit to api is successful - not on submit button click @KBandipo

**Review by Ifycode — CHANGES_REQUESTED** [review]

**Comment by KBandipo** [comment]
Ready for review

**Comment by KBandipo** [comment]
Ready for review

**Review by Ifycode — APPROVED** [review]
Clean, neat 👌🏽
Nice work.
